sudo: required
services:
 - docker:
 
before_install:
 - docker build -t sandocker/docker-react -f Dockerfile.dev .
 
script:
 - docker run -e CI=true sandocker/docker-react npm run test
 
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 env: "dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-2-040320628169"
 bucket_path: "docker"
 on:
  branch: master
  access_key_id: "$MY_KEY"
  secret_access_key: "$MY_OK"